/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2019-12-18 17:50:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import domain.Member;

public final class member_002dinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1576685459589L));
    _jspx_dependants.put("jar:file:/C:/Users/ParkSM/Desktop/JspInUniv/2a201612015/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/park-shop/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1576685459314L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1576688227522L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("domain.Member");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <!-- Required meta tags -->\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <title>aranaz</title>\r\n");
      out.write("  <link rel=\"icon\" href=\"img/favicon.png\">\r\n");
      out.write("  <!-- Bootstrap CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("  <!-- animate CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("  <!-- owl carousel CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("  <!-- nice select CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/nice-select.css\">\r\n");
      out.write("  <!-- font awesome CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/all.css\">\r\n");
      out.write("  <!-- flaticon CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/flaticon.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/themify-icons.css\">\r\n");
      out.write("  <!-- font awesome CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("  <!-- swiper CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/slick.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/price_rangs.css\">\r\n");
      out.write("  <!-- style CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("  <script language='javascript'>\r\n");
      out.write(" \tfunction formChk(){\r\n");
      out.write("\t    if (document.regForm.pw.value=='') {\r\n");
      out.write("\t      alert(\"암호를 입력하세요!!\");   \r\n");
      out.write("\t      document.regForm.pw.focus();\r\n");
      out.write("\t    } else if(document.regForm.name.value=='') {\r\n");
      out.write("\t       alert(\"이름을 입력해주세요!!\");\r\n");
      out.write("\t       document.regForm.name.focus();\r\n");
      out.write("\t    } else\r\n");
      out.write("\t    \tdocument.regForm.submit();\r\n");
      out.write("\t    \r\n");
      out.write(" \t}\r\n");
      out.write(" \t\r\n");
      out.write(" \tfunction deleteID() {\r\n");
      out.write(" \t\tdeleteForm.submit();\r\n");
      out.write(" \t}\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!--::header part start::-->\r\n");
      out.write("  ");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <header class=\"main_menu home_menu\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("                        <a class=\"navbar-brand\" href=\"index.jsp\"> <img src=\"img/logo.png\" alt=\"logo\"> </a>\r\n");
      out.write("                        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("                            data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\"\r\n");
      out.write("                            aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                            <span class=\"menu_icon\"><i class=\"fas fa-bars\"></i></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"collapse navbar-collapse main-menu-item\" id=\"navbarSupportedContent\">\r\n");
      out.write("                            <ul class=\"navbar-nav\">\r\n");
      out.write("                                <li class=\"nav-item\">\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"member-list.do\">Members</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"nav-item dropdown\">\r\n");
      out.write("                                    <a class=\"nav-link dropdown-toggle\" href=\"blog.jsp\" id=\"navbarDropdown_1\"\r\n");
      out.write("                                        role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                        Shop\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown_1\">\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"category.jsp\"> shop category</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"product-list.do\">product lists</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"nav-item dropdown\">\r\n");
      out.write("                                    <a class=\"nav-link dropdown-toggle\" href=\"blog.jsp\" id=\"navbarDropdown_3\"\r\n");
      out.write("                                        role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                        pages\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown_2\">\r\n");
      out.write("                                    \t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                        \r\n");
      out.write("                                         ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"member-list.do\">member-list</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"checkout.jsp\">product checkout</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"cart.jsp\">shopping cart</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"confirmation.jsp\">confirmation</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"elements.jsp\">elements</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"nav-item dropdown\">\r\n");
      out.write("                                    <a class=\"nav-link dropdown-toggle\" href=\"blog.jsp\" id=\"navbarDropdown_2\"\r\n");
      out.write("                                        role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                        blog\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown_2\">\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"blog.jsp\"> blog</a>\r\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"single-blog.jsp\">Single blog</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                \r\n");
      out.write("                                <li class=\"nav-item\">\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"contact.jsp\">Contact</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"hearer_icon d-flex\">\r\n");
      out.write("                            <a id=\"search_1\" href=\"javascript:void(0)\"><i class=\"ti-search\"></i></a>\r\n");
      out.write("                            \r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                     \r\n");
      out.write("                            \r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"dropdown cart\">\r\n");
      out.write("                                <a class=\"dropdown-toggle\" href=\"./product-list.do\" id=\"navbarDropdown3\" role=\"button\">\r\n");
      out.write("                                    <i class=\"fas fa-cart-plus\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <!-- <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                                    <div class=\"single_product\">\r\n");
      out.write("    \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div> -->\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>");
      out.write("\r\n");
      out.write("  <!-- Header part end-->\r\n");
      out.write("\r\n");
      out.write("  <!--================Home Banner Area =================-->\r\n");
      out.write("  <!-- breadcrumb start-->\r\n");
      out.write("  <section class=\"breadcrumb breadcrumb_bg\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\"col-lg-8\">\r\n");
      out.write("          <div class=\"breadcrumb_iner\">\r\n");
      out.write("            <div class=\"breadcrumb_iner_item\">\r\n");
      out.write("              <h2>Member Registration</h2>\r\n");
      out.write("              <p>Home <span>-</span> Shop Single</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  <!-- breadcrumb start-->\r\n");
      out.write("\r\n");
      out.write("  <!--================Checkout Area =================-->\r\n");
      out.write("  <section class=\"checkout_area padding_top\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("     \r\n");
      out.write("      <div class=\"cupon_area\">\r\n");
      out.write("      \t<h2>Apply Coupon</h2>\r\n");
      out.write("        <div class=\"check_title\">\r\n");
      out.write("          <h2>Have a coupon?&nbsp<a href=\"#\">Click here to enter your code</a></h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input type=\"text\" placeholder=\"Enter coupon code\" />\r\n");
      out.write("        <a class=\"tp_btn\" href=\"#\">Apply Coupon</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"billing_details\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-8\">\r\n");
      out.write("          \t<h2>Member Information</h2>\r\n");
      out.write("\t          <div class=\"check_title\">\r\n");
      out.write("\t\t          <h2>Please enter your information</h2>\r\n");
      out.write("\t          </div>\t\r\n");
      out.write("\t       \t<br>\r\n");
      out.write("            <form class=\"row contact_form\" id=\"regForm\" name=\"regForm\" action=\"member-edit.do\" method=\"post\" novalidate=\"novalidate\">\r\n");
      out.write("              <div class=\"col-md-6 form-group p_star\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"first\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.model_info.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"ID\" readonly />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-6 form-group p_star\">\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" id=\"last\" name=\"pw\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.model_info.pw}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Password\" readonly/>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-12 form-group\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.model_info.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Company name\" />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-6 form-group p_star\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"phone\" name=\"phone\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.model_info.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Phone number\" />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-6 form-group p_star\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"email\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.model_info.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Email address\" />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-12 form-group p_star\">\r\n");
      out.write("                <select name=\"country\" class=\"country_select\">\r\n");
      out.write("                \t");

                		String c = ((Member)request.getAttribute("model_info")).getCountry();
                		if(c.equals("1")) {
                	
      out.write("\r\n");
      out.write("\t\t                  <option value=\"1\" selected>한국</option>\r\n");
      out.write("\t\t                  <option value=\"2\">미국</option>\r\n");
      out.write("\t\t                  <option value=\"4\">스페인</option>\r\n");
      out.write("\t\t            ");

                		} else if (c.equals("2")) {
		            
      out.write("\r\n");
      out.write("\t\t            \t  <option value=\"1\">한국</option>\r\n");
      out.write("\t\t                  <option value=\"2\" selected>미국</option>\r\n");
      out.write("\t\t                  <option value=\"4\">스페인</option>\r\n");
      out.write("\t\t            ");

                		} else if (c.equals("4")) {
		            
      out.write("     \r\n");
      out.write("\t\t            \t  <option value=\"1\">한국</option>\r\n");
      out.write("\t\t                  <option value=\"2\">미국</option>\r\n");
      out.write("\t\t                  <option value=\"4\" selected>스페인</option>\r\n");
      out.write("                    ");

                  	  }
                    
      out.write("\r\n");
      out.write("\t\t            \r\n");
      out.write("                </select>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-6 form-group p_star\">\r\n");
      out.write("\t              <a href=\"#\" class=\"genric-btn info circle arrow\" onClick=\"formChk();\"><span class=\"lnr lnr-arrow-right\">정보수정</span></a>\r\n");
      out.write("\t              <a href=\"#\" class=\"genric-btn info circle arrow\" onClick=\"deleteID();\"><span class=\"lnr lnr-arrow-right\">회원탈퇴</span></a>\r\n");
      out.write("\t          </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("          \r\n");
      out.write("          <form style=\"display:none;\" id=\"deleteForm\" name=\"deleteForm\" action=\"member-delete.do\" method=\"post\">\r\n");
      out.write("          \t<input type=\"text\" id=\"id\" name=\"id\" style=\"display:none;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.model_info.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> \r\n");
      out.write("          </form>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"col-lg-4\">\r\n");
      out.write("            <div class=\"order_box\">\r\n");
      out.write("              <h2>Your Order</h2>\r\n");
      out.write("              <ul class=\"list\">\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"#\">Product\r\n");
      out.write("                    <span>Total</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"#\">Fresh Blackberry\r\n");
      out.write("                    <span class=\"middle\">x 02</span>\r\n");
      out.write("                    <span class=\"last\">$720.00</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"#\">Fresh Tomatoes\r\n");
      out.write("                    <span class=\"middle\">x 02</span>\r\n");
      out.write("                    <span class=\"last\">$720.00</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"#\">Fresh Brocoli\r\n");
      out.write("                    <span class=\"middle\">x 02</span>\r\n");
      out.write("                    <span class=\"last\">$720.00</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("              <ul class=\"list list_2\">\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"#\">Subtotal\r\n");
      out.write("                    <span>$2160.00</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"#\">Shipping\r\n");
      out.write("                    <span>Flat rate: $50.00</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"#\">Total\r\n");
      out.write("                    <span>$2210.00</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("              <div class=\"payment_item\">\r\n");
      out.write("                <div class=\"radion_btn\">\r\n");
      out.write("                  <input type=\"radio\" id=\"f-option5\" name=\"selector\" />\r\n");
      out.write("                  <label for=\"f-option5\">Check payments</label>\r\n");
      out.write("                  <div class=\"check\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p>\r\n");
      out.write("                  Please send a check to Store Name, Store Street, Store Town,\r\n");
      out.write("                  Store State / County, Store Postcode.\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"payment_item active\">\r\n");
      out.write("                <div class=\"radion_btn\">\r\n");
      out.write("                  <input type=\"radio\" id=\"f-option6\" name=\"selector\" />\r\n");
      out.write("                  <label for=\"f-option6\">Paypal </label>\r\n");
      out.write("                  <img src=\"img/product/single-product/card.jpg\" alt=\"\" />\r\n");
      out.write("                  <div class=\"check\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p>\r\n");
      out.write("                  Please send a check to Store Name, Store Street, Store Town,\r\n");
      out.write("                  Store State / County, Store Postcode.\r\n");
      out.write("                </p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"creat_account\">\r\n");
      out.write("                <input type=\"checkbox\" id=\"f-option4\" name=\"selector\" />\r\n");
      out.write("                <label for=\"f-option4\">I’ve read and accept the </label>\r\n");
      out.write("                <a href=\"#\">terms & conditions*</a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <a class=\"btn_3\" href=\"#\">Proceed to Paypal</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  <!--================End Checkout Area =================-->\r\n");
      out.write("\r\n");
      out.write("  <!--::footer_part start::-->\r\n");
      out.write("  ");
      out.write("<footer class=\"footer_part\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row justify-content-around\">\r\n");
      out.write("                <div class=\"col-sm-6 col-lg-2\">\r\n");
      out.write("                    <div class=\"single_footer_part\">\r\n");
      out.write("                        <h4>Top Products</h4>\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                            <li><a href=\"\">Managed Website</a></li>\r\n");
      out.write("                            <li><a href=\"\">Manage Reputation</a></li>\r\n");
      out.write("                            <li><a href=\"\">Power Tools</a></li>\r\n");
      out.write("                            <li><a href=\"\">Marketing Service</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-6 col-lg-2\">\r\n");
      out.write("                    <div class=\"single_footer_part\">\r\n");
      out.write("                        <h4>Quick Links</h4>\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                            <li><a href=\"\">Jobs</a></li>\r\n");
      out.write("                            <li><a href=\"\">Brand Assets</a></li>\r\n");
      out.write("                            <li><a href=\"\">Investor Relations</a></li>\r\n");
      out.write("                            <li><a href=\"\">Terms of Service</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-6 col-lg-2\">\r\n");
      out.write("                    <div class=\"single_footer_part\">\r\n");
      out.write("                        <h4>Features</h4>\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                            <li><a href=\"\">Jobs</a></li>\r\n");
      out.write("                            <li><a href=\"\">Brand Assets</a></li>\r\n");
      out.write("                            <li><a href=\"\">Investor Relations</a></li>\r\n");
      out.write("                            <li><a href=\"\">Terms of Service</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-6 col-lg-2\">\r\n");
      out.write("                    <div class=\"single_footer_part\">\r\n");
      out.write("                        <h4>Resources</h4>\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                            <li><a href=\"\">Guides</a></li>\r\n");
      out.write("                            <li><a href=\"\">Research</a></li>\r\n");
      out.write("                            <li><a href=\"\">Experts</a></li>\r\n");
      out.write("                            <li><a href=\"\">Agencies</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-6 col-lg-4\">\r\n");
      out.write("                    <div class=\"single_footer_part\">\r\n");
      out.write("                        <h4>Newsletter</h4>\r\n");
      out.write("                        <p>Heaven fruitful doesn't over lesser in days. Appear creeping\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <div id=\"mc_embed_signup\">\r\n");
      out.write("                            <form target=\"_blank\"\r\n");
      out.write("                                action=\"https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01\"\r\n");
      out.write("                                method=\"get\" class=\"subscribe_form relative mail_part\">\r\n");
      out.write("                                <input type=\"email\" name=\"email\" id=\"newsletter-form-email\" placeholder=\"Email Address\"\r\n");
      out.write("                                    class=\"placeholder hide-on-focus\" onfocus=\"this.placeholder = ''\"\r\n");
      out.write("                                    onblur=\"this.placeholder = ' Email Address '\">\r\n");
      out.write("                                <button type=\"submit\" name=\"submit\" id=\"newsletter-submit\"\r\n");
      out.write("                                    class=\"email_icon newsletter-submit button-contactForm\">subscribe</button>\r\n");
      out.write("                                <div class=\"mt-10 info\"></div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"copyright_part\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-8\">\r\n");
      out.write("                        <div class=\"copyright_text\">\r\n");
      out.write("                            <P><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"ti-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></P>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <div class=\"footer_icon social_icon\">\r\n");
      out.write("                            <ul class=\"list-unstyled\">\r\n");
      out.write("                                <li><a href=\"#\" class=\"single_social_icon\"><i class=\"fab fa-facebook-f\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\" class=\"single_social_icon\"><i class=\"fab fa-twitter\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\" class=\"single_social_icon\"><i class=\"fas fa-globe\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\" class=\"single_social_icon\"><i class=\"fab fa-behance\"></i></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>");
      out.write("\r\n");
      out.write("  <!--::footer_part end::-->\r\n");
      out.write("\r\n");
      out.write("  <!-- jquery plugins here-->\r\n");
      out.write("  <!-- jquery -->\r\n");
      out.write("  <script src=\"js/jquery-1.12.1.min.js\"></script>\r\n");
      out.write("  <!-- popper js -->\r\n");
      out.write("  <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("  <!-- bootstrap js -->\r\n");
      out.write("  <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("  <!-- easing js -->\r\n");
      out.write("  <script src=\"js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("  <!-- swiper js -->\r\n");
      out.write("  <script src=\"js/swiper.min.js\"></script>\r\n");
      out.write("  <!-- swiper js -->\r\n");
      out.write("  <script src=\"js/masonry.pkgd.js\"></script>\r\n");
      out.write("  <!-- particles js -->\r\n");
      out.write("  <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("  <!-- slick js -->\r\n");
      out.write("  <script src=\"js/slick.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.counterup.min.js\"></script>\r\n");
      out.write("  <script src=\"js/waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"js/contact.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.form.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.validate.min.js\"></script>\r\n");
      out.write("  <script src=\"js/mail-script.js\"></script>\r\n");
      out.write("  <script src=\"js/stellar.js\"></script>\r\n");
      out.write("  <script src=\"js/price_rangs.js\"></script>\r\n");
      out.write("  <!-- custom js -->\r\n");
      out.write("  <script src=\"js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /header.jsp(36,37) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.login != 'success' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                        \t<a class=\"dropdown-item\" href=\"login.jsp\"> login</a>\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t                            ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t                        ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /header.jsp(41,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.login_id == 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t                            \t<a class=\"dropdown-item\" href=\"product-register.jsp\">product register</a>\r\n");
          out.write("\t\t\t\t                            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                            ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t                            ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /header.jsp(72,29) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.login != 'success'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                            \t<a href=\"login.jsp\"><i class=\"ti-heart-broken\"></i></a>\r\n");
          out.write("\t                            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                            \t<a href='confirm-pw.jsp?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.login_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'><i class=\"ti-user\"></i></button>\r\n");
          out.write("\t                            \t<a href=\"logout.jsp\"><i class=\"ti-arrow-right\"></i></a>\r\n");
          out.write("\t                            ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
